image: ruby:2.3

before_script:
  - bundle install

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - gh-pages
  tags:
  - swc-bb

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  tags:
  - swc-bb
  artifacts:
    paths:
    - test
